### ISSUE TITLE
Sharing Doesn't Copy

### ISSUE THREAD

**Issue by josolanes** [modem7/react-wordle#14]
I updated earlier this morning with the latest tag and sharing seems to have stopped working. Clicking the Share button after completing it no longer copies anything to the clipboard.

I saw in the other issue you referenced https://reactle.vercel.app/ so I tried to reproduce it, but sharing copies the results as expected there.

Thank you for your work on this!

EDIT:
I've confirmed this on Android Chrome, Windows Chrome, and Linux Chrome

**Comment by modem7** [comment]
No worries!

What I'm looking to do, is recreate the entire project from scratch and recreating the image from upstream.

Might take until the weekend depending how work goes, but bear with me and I'll get on it!

In the meantime, there's a legacy tag which is the old version that's unmodified.

**Comment by josolanes** [comment]
Excellent thank you so much @modem7 !

**Comment by modem7** [comment]
Just an update, it looks like the upstream may also be having this issue. 

I've submitted an issue and hopefully we'll get it resolved relatively quickly. 

Good to know it wasn't (just) something I did! :P

If you wish, you can test this yourself by doing:

```bash
git clone https://github.com/cwackerfuss/react-wordle.git &&
cd react-wordle/ &&
docker build --no-cache --target=prod -t wordle:test -f docker/Dockerfile . &&
docker run -d -p 80:8080 --name reactle-prod wordle:test &&
cd ../ && rm -rf ./react-wordle
```

Open browser to serverIP:80

Then when you're done

```bash
docker container stop reactle-prod; docker container rm reactle-prod; docker image prune -af
```

**Comment by modem7** [comment]
@josolanes Turns out this is an intentional functionality from browsers when a site isn't hosted via https. 

https://github.com/cwackerfuss/react-wordle/issues/331#issuecomment-1073155476

If you host it via https instead of local, the functionality works as intended. 

This is how I tested:

```yaml
  wordle:
    image: modem7/wordle
    container_name: Wordle
    ports:
      - 80:8080
    networks:
      pihole:
    labels: 
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wordletest-rtr.entrypoints=https"
      - "traefik.http.routers.wordletest-rtr.rule=Host(`wordletest.$DOMAINNAME`)"
      - "traefik.http.routers.wordletest-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.wordletest-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.wordletest-rtr.service=wordletest-svc"
      - "traefik.http.services.wordletest-svc.loadbalancer.server.port=8080"
```

Could you confirm that works on your end and then we can look at closing the issue if so.
