### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Martynet** [modem7/react-wordle#15]
Hello,
I'm running Wordle container in Docker/Synology. But it stopped working after Watcher updated it.
Did you change the port from 4111 to 8080? I'm using 8080 port for other container... Is there any way to fix it please? Thank you

**Comment by modem7** [comment]
Heya, 

Yupper, due to the change in the base image not running as root, I had to change the port from 80 to 8080.

You can set a forwarding port for the Docker container. 

E.g.

```yaml
version: "2.4"

services:

  wordle:
    image: modem7/wordle:latest
    container_name: Wordle
    ports:
      - 4111:8080
```

The left port can be whatever you wish, as long as the port on the right is the container's internal/exposed port, this won't affect any other containers. 

Please let me know how you get on.
